Added STATIC_ASSERT
STATIC_ASSERT(condition) macro has been added. It is for the
compile-time assertion and will fail to be compiled if the given
condition does not hold. A typical compilation error message is as
follows:
  form3.h:213:1: error: size of array 'static_assertion_failed_213' is
  negative
And some static assertions for data size have been added.